#!/bin/bash
clear
printf "This is information provided by mysystem.sh. Program starts now."

printf "Hello, $USER"


printf "Today's date is 'date', this is week 'date +"%V"'.\n\n"

printf "These users are currently connected:\n"
w | cut -d " " -f 1 - | grep -v USER | sort -u
printf "\n"

printf "This is 'uname -s' running on a 'uname -m' processor."


printf "This is the uptime information:"
uptime
printf "\n"

printf "That's all folks!\n"
